[2024-09-22 05:19:43,831] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:19:38.441593+00:00 [queued]>
[2024-09-22 05:19:43,841] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:19:38.441593+00:00 [queued]>
[2024-09-22 05:19:43,842] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 05:19:43,842] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2024-09-22 05:19:43,843] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 05:19:43,856] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): conexion_BD> on 2024-09-22 05:19:38.441593+00:00
[2024-09-22 05:19:43,860] {standard_task_runner.py:52} INFO - Started process 2094 to run task
[2024-09-22 05:19:43,863] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Regions_ETL', 'conexion_BD', 'manual__2024-09-22T05:19:38.441593+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Regions.py', '--cfg-path', '/tmp/tmp4zxi8usy', '--error-file', '/tmp/tmpns1_m1a3']
[2024-09-22 05:19:43,863] {standard_task_runner.py:77} INFO - Job 28: Subtask conexion_BD
[2024-09-22 05:19:43,916] {logging_mixin.py:109} INFO - Running <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:19:38.441593+00:00 [running]> on host 61d34902ebae
[2024-09-22 05:19:43,946] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-09-22 05:19:43,967] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=flores_laura14
AIRFLOW_CTX_DAG_ID=Regions_ETL
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2024-09-22T05:19:38.441593+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-22T05:19:38.441593+00:00
[2024-09-22 05:19:43,968] {logging_mixin.py:109} INFO - Conectandose a la BD en la fecha: 2024-09-22 5
[2024-09-22 05:19:46,067] {logging_mixin.py:109} INFO - Unable to connect to Redshift.
[2024-09-22 05:19:46,068] {logging_mixin.py:109} INFO - connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
[2024-09-22 05:19:46,069] {logging_mixin.py:109} INFO - 
[2024-09-22 05:19:46,070] {python.py:175} INFO - Done. Returned value was: None
[2024-09-22 05:19:46,093] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=Regions_ETL, task_id=conexion_BD, execution_date=20240922T051938, start_date=20240922T051943, end_date=20240922T051946
[2024-09-22 05:19:46,131] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-09-22 05:19:46,178] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
