[2024-09-22 05:18:34,106] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:18:27.243995+00:00 [queued]>
[2024-09-22 05:18:34,118] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:18:27.243995+00:00 [queued]>
[2024-09-22 05:18:34,118] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 05:18:34,119] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2024-09-22 05:18:34,119] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 05:18:34,133] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): conexion_BD> on 2024-09-22 05:18:27.243995+00:00
[2024-09-22 05:18:34,137] {standard_task_runner.py:52} INFO - Started process 2036 to run task
[2024-09-22 05:18:34,140] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Regions_ETL', 'conexion_BD', 'manual__2024-09-22T05:18:27.243995+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Regions.py', '--cfg-path', '/tmp/tmpxh0m56fr', '--error-file', '/tmp/tmp0s7s6808']
[2024-09-22 05:18:34,142] {standard_task_runner.py:77} INFO - Job 24: Subtask conexion_BD
[2024-09-22 05:18:34,221] {logging_mixin.py:109} INFO - Running <TaskInstance: Regions_ETL.conexion_BD manual__2024-09-22T05:18:27.243995+00:00 [running]> on host 61d34902ebae
[2024-09-22 05:18:34,253] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-09-22 05:18:34,275] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=flores_laura14
AIRFLOW_CTX_DAG_ID=Regions_ETL
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2024-09-22T05:18:27.243995+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-22T05:18:27.243995+00:00
[2024-09-22 05:18:34,276] {logging_mixin.py:109} INFO - Conectandose a la BD en la fecha: 2024-09-22 5
[2024-09-22 05:18:36,229] {logging_mixin.py:109} INFO - Unable to connect to Redshift.
[2024-09-22 05:18:36,230] {logging_mixin.py:109} INFO - connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
[2024-09-22 05:18:36,230] {logging_mixin.py:109} INFO - 
[2024-09-22 05:18:36,231] {python.py:175} INFO - Done. Returned value was: None
[2024-09-22 05:18:36,240] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=Regions_ETL, task_id=conexion_BD, execution_date=20240922T051827, start_date=20240922T051834, end_date=20240922T051836
[2024-09-22 05:18:36,287] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-09-22 05:18:36,320] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
