[2024-09-22 04:33:50,051] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22 04:33:50,075] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.conexion_BD scheduled__2024-09-21T00:00:00+00:00 [queued]>
[2024-09-22 04:33:50,076] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 04:33:50,077] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2024-09-22 04:33:50,077] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-09-22 04:33:50,099] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): conexion_BD> on 2024-09-21 00:00:00+00:00
[2024-09-22 04:33:50,114] {standard_task_runner.py:52} INFO - Started process 194 to run task
[2024-09-22 04:33:50,118] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Regions_ETL', 'conexion_BD', 'scheduled__2024-09-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Regions.py', '--cfg-path', '/tmp/tmpf4jgolqo', '--error-file', '/tmp/tmp0tmpuc4s']
[2024-09-22 04:33:50,119] {standard_task_runner.py:77} INFO - Job 6: Subtask conexion_BD
[2024-09-22 04:33:50,198] {logging_mixin.py:109} INFO - Running <TaskInstance: Regions_ETL.conexion_BD scheduled__2024-09-21T00:00:00+00:00 [running]> on host 61d34902ebae
[2024-09-22 04:33:50,244] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-09-22 04:33:50,275] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=flores_laura14
AIRFLOW_CTX_DAG_ID=Regions_ETL
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-21T00:00:00+00:00
[2024-09-22 04:33:50,276] {logging_mixin.py:109} INFO - Conectandose a la BD en la fecha: 2024-09-21 0
[2024-09-22 04:33:51,815] {logging_mixin.py:109} INFO - Unable to connect to Redshift.
[2024-09-22 04:33:51,816] {logging_mixin.py:109} INFO - connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
connection to server at "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" (52.44.43.227), port 5439 failed: FATAL:  password authentication failed for user "flores_laura14_coderhouse"
[2024-09-22 04:33:51,817] {logging_mixin.py:109} INFO - 
[2024-09-22 04:33:51,817] {python.py:175} INFO - Done. Returned value was: None
[2024-09-22 04:33:51,838] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=Regions_ETL, task_id=conexion_BD, execution_date=20240921T000000, start_date=20240922T043350, end_date=20240922T043351
[2024-09-22 04:33:51,901] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-09-22 04:33:51,951] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
